Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,14 +26,14 @@ jobs:
       # - name: Install dependencies (with skipping tests)
       #   run: mvn package -DskipTests -Drat.skip=true -Dcheckstyle.skip -Dmaven.test.skip=true -U
   
-      # - name: Run NonDex to check for flaky tests
-      #   run: mvn -pl standalone-metastore/metastore-server edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=org.apache.hadoop.hive.metastore.TestPartitionManagement#testPartitionDiscoveryNonDefaultCatalog -Drat.skip=true -DnondexRuns=10 -U
+      - name: Run NonDex to check for flaky tests
+        run: mvn -pl standalone-metastore/metastore-server edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=org.apache.hadoop.hive.metastore.TestPartitionManagement#testPartitionDiscoveryNonDefaultCatalog -Drat.skip=true -DnondexRuns=10 -DfailIfNoTests=false -U
       
-      - name: Get nondexTests
-        run: nondexTests=$(git diff --name-status --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} | grep /test/ | sed -e 's;.*test/java/;;' -e 's/.java//' -e 's;/;.;g' | tr '\n' ','); echo $nondexTests;
-      - name: Run NonDex
-        run: if [ ! -z $nondexTests ]; then printf "Running NonDex on tests:\n$nondexTests \n" ; mvn -B edu.illinois:nondex-maven-plugin:2.1.7:nondex  -Dtest=org.apache.hadoop.hive.metastore.TestPartitionManagement#testPartitionDiscoveryNonDefaultCatalog -DnondexRuns=20 -DfailIfNoTests=false -Dtest=$nondexTests ; fi
-      - name: Find flakyTests 
-        run: if [ -d ".nondex" ]; then flakyTests=$(awk ' !x[$0]++' .nondex/*/failures); fi
-      - name: Output flakyTests
-        run: if [ ! -z "$flakyTests" ]; then printf "Found flaky tests:\n$flakyTests \n" ; exit 1 ; else printf "No flaky tests found.\n" ; fi 
+      # - name: Get nondexTests
+      #   run: nondexTests=$(git diff --name-status --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} | grep /test/ | sed -e 's;.*test/java/;;' -e 's/.java//' -e 's;/;.;g' | tr '\n' ','); echo $nondexTests;
+      # - name: Run NonDex
+      #   run: if [ ! -z $nondexTests ]; then printf "Running NonDex on tests:\n$nondexTests \n" ; mvn -B edu.illinois:nondex-maven-plugin:2.1.7:nondex  -Dtest=org.apache.hadoop.hive.metastore.TestPartitionManagement#testPartitionDiscoveryNonDefaultCatalog -DnondexRuns=20 -DfailIfNoTests=false -Dtest=$nondexTests ; fi
+      # - name: Find flakyTests 
+      #   run: if [ -d ".nondex" ]; then flakyTests=$(awk ' !x[$0]++' .nondex/*/failures); fi
+      # - name: Output flakyTests
+      #   run: if [ ! -z "$flakyTests" ]; then printf "Found flaky tests:\n$flakyTests \n" ; exit 1 ; else printf "No flaky tests found.\n" ; fi 
